# Camera credentials belong in backend/.env.  Keeping an empty CLI fallback
# prevents them from appearing in source control, process listings, or logs.
DEFAULT_RTSP_URL = ""
DISPLAY_SIZE = (1280, 720)
TACTICAL_MAP_SIZE = 600
DEFAULT_TACTICAL_MAP_SIZE_CM = 480
DEFAULT_TACTICAL_MAP_GRID_COLUMNS = 5
DEFAULT_TACTICAL_MAP_GRID_ROWS = 5
LEFT_ANKLE_KEYPOINT_INDEX = 15
RIGHT_ANKLE_KEYPOINT_INDEX = 16
MIN_ANKLE_CONFIDENCE = 0.35
DEFAULT_FUSION_DISTANCE_CM = 50.0
DEFAULT_MEDIAPIPE_MODEL_PATH = "pose_landmarker_full.task"
MEDIAPIPE_LEFT_ANKLE = 27
MEDIAPIPE_RIGHT_ANKLE = 28
MEDIAPIPE_LEFT_HEEL = 29
MEDIAPIPE_RIGHT_HEEL = 30
MEDIAPIPE_LEFT_FOOT_INDEX = 31
MEDIAPIPE_RIGHT_FOOT_INDEX = 32
MIN_MEDIAPIPE_VISIBILITY = 0.45
MEDIAPIPE_NOSE = 0
MEDIAPIPE_LEFT_EYE = 2
MEDIAPIPE_RIGHT_EYE = 5
MEDIAPIPE_LEFT_SHOULDER = 11
MEDIAPIPE_RIGHT_SHOULDER = 12
MEDIAPIPE_LEFT_HIP = 23
MEDIAPIPE_RIGHT_HIP = 24
MEDIAPIPE_LEFT_KNEE = 25
MEDIAPIPE_RIGHT_KNEE = 26
MIN_ANATOMICAL_ANCHOR_PIXELS = 4.0
MIN_ANATOMICAL_FULL_BODY_PIXELS = 25.0
MIN_ANATOMICAL_RATIO = 0.04
MAX_ANATOMICAL_RATIO = 0.17
MIN_INITIAL_FOOT_VISIBILITY = 0.70
HEAD_DOWN_ANCHOR_FRACTION = 0.35
MIN_HEAD_DOWN_PIXELS = 6.0
DEFAULT_ANATOMICAL_RATIO_EMA_ALPHA = 0.02
DEFAULT_MAX_FOOT_JUMP_PIXELS_PER_FRAME = 120.0
DEFAULT_MAX_PERSON_SPEED_MPS = 8.0
DEFAULT_MAP_POSITION_EMA_ALPHA = 0.35
DEFAULT_POSE_DROPOUT_TTL_FRAMES = 30
DEFAULT_YOLO_NMS_IOU = 0.55
DEFAULT_TRACKER_CONFIG_PATH = "bytetrack_ghost_resistant.yaml"
DEFAULT_REID_DISTANCE_THRESHOLD = 0.30
DEFAULT_REID_SIMILARITY_THRESHOLD = 1.0 - DEFAULT_REID_DISTANCE_THRESHOLD
DEFAULT_REID_MEMORY_TTL_FRAMES = 450
DEFAULT_REID_EMA_ALPHA = 0.2
# A newly spawned local track is treated as a possible ByteTrack shadow only
# when it almost completely overlaps an older track in the same camera.
# Appearance still has the final say before an ID handoff is committed.
DEFAULT_REID_SHADOW_IOU_THRESHOLD = 0.65
DEFAULT_REID_SHADOW_CONTAINMENT_THRESHOLD = 0.85
DEFAULT_REID_SHADOW_CENTER_DISTANCE_RATIO = 0.20
DEFAULT_REID_SHADOW_PROBATION_FRAMES = 3
DEFAULT_REID_SHADOW_SEPARATION_FRAMES = 2
REID_GALLERY_SLOTS = ("baseline", "front", "back", "left_side", "right_side")
REID_SEMANTIC_SLOTS = REID_GALLERY_SLOTS[1:]
DEFAULT_REID_BLUR_THRESHOLD = 100.0
DEFAULT_REID_SEMANTIC_CONFIDENCE = 0.75
DEFAULT_REID_INTAKE_DELAY_SECONDS = 0.5
DEFAULT_REID_INTAKE_TIMEOUT_SECONDS = 5.0
DEFAULT_REID_SEMANTIC_COOLDOWN_FRAMES = 30
DEFAULT_REID_SEMANTIC_RETRY_FRAMES = 10
DEFAULT_REID_QUEUE_SIZE = 64
DEFAULT_REID_INTAKE_RETRY_FRAMES = 15
DEFAULT_REID_MAX_RETRY_FRAMES = 240
DEFAULT_REID_CROP_SIDE_PADDING = 0.02
DEFAULT_REID_CROP_TOP_PADDING = 0.02
DEFAULT_REID_CROP_BOTTOM_PADDING = 0.10
DEFAULT_REID_CROP_MAX_INTRUDER_AREA_RATIO = 0.15
DEFAULT_REID_FRAME_EDGE_MARGIN_PIXELS = 2.0
DEFAULT_REID_ROLE_CHECKPOINT = "evacuation_mobilenet_v1.pth"
DEFAULT_REID_ROLE_CONFIDENCE = 0.60
DEFAULT_CROSS_CAMERA_MAX_SKEW_SECONDS = 0.35
# A location pair becomes one provisional person after a short, repeated
# agreement.  ReID can confirm it sooner, while a longer clean location
# streak provides a fallback when the cameras only see opposite body angles.
DEFAULT_PROVISIONAL_PAIR_FRAMES = 3
DEFAULT_PROVISIONAL_LOCATION_CONFIRM_FRAMES = 12
DEFAULT_PROVISIONAL_HOLD_GRACE_FRAMES = 5
DEFAULT_PROVISIONAL_HOLD_MAX_FRAMES = 12
DEFAULT_PROVISIONAL_CHALLENGE_DISTANCE = 0.55
FPS_EMA_ALPHA = 0.1
