from cag_dashboard.views.cameras import render_camera_panel, render_stitched_feed
from cag_dashboard.views.floorplan import render_floorplan
from cag_dashboard.views.header import render_header
from cag_dashboard.views.health import render_count_chart, render_events, render_system_health
from cag_dashboard.views.overview import render_alert_strip, render_primary_status
from cag_dashboard.views.people import render_registered_persons
from cag_dashboard.views.technical import render_technical_view
